version: '3.5'

services:
  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    tty: true
    networks:
      - fullcycle
    environment:
      - MYSQL_ROOT_PASSWORD=fullcycle
      - MYSQL_DATABASE=fullcycle
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s npm run start
    networks:
      - fullcycle
    ports:
      - 8081:3000
    tty: true
    environment:
      - PORT=3000
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=fullcycle
      - MYSQL_DB=fullcycle
    depends_on:
      - db
  server:
    build:
      context: server
    container_name: server
    ports:
      - 8080:80
    networks:
      - fullcycle
    depends_on:
      - db
      - app

networks:
  fullcycle:
    name: fullcycle
    driver: bridge
